highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://d2an3.github.io
author: Andrei Dan

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Andrei Dan's Personal Web Page
name: Andrei Dan
email: d2an3m@gmail.com
email_full: mailto:d2an3m@gmail.com
website: d2an3.github.io
website_full: https://d2an3.github.io
github: d2an3
twitter: d2an3
# tel: +44 0000 000000
# tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/CYKtruXQiFZW1r856'
address: 
  street: Power Grids Research, Segelhofstrasse 1A
  postcode: CH-5405
  city: Baden 
  country: Switzerland
# google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
